# Generated by Django 5.2.5 on 2025-11-27 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_producto_imagen_alter_usuario_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('idDireccion', models.AutoField(primary_key=True, serialize=False)),
                ('alias', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='main.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='main.direccion'),
        ),
    ]
