# Generated by Django 5.2.5 on 2025-11-28 05:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_producto_tipo_alter_direccion_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('idFavorito', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='main.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='main.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'producto')},
            },
        ),
    ]
